version: "3"

services:
  postgres:
    image: 'postgres:15'
    container_name: 'ideas-bd'
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'

  app:
    build: ./
    container_name: 'ideas-app'
    environment:
      - 'DB_URL=${DB_URL}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'MAIL_EMAIL=${MAIL_EMAIL}'
      - 'MAIL_PASSWORD=${MAIL_PASSWORD}'
      - 'JWT_SECRET=${JWT_SECRET}'
      - 'AWS_ID=${AWS_ID}'
      - 'AWS_KEY=${AWS_KEY}'
      - 'AWS_BUCKET=${AWS_BUCKET}'
      - 'SPRING_PROFILES_ACTIVE=dev'
    depends_on:
      - postgres
    ports:
      - "8080:8080"
