app:
  user:
    default-avatars: defaultAvatar_1.png, defaultAvatar_2.png, defaultAvatar_3.png
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: alex21022001
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: Europe/Kiev
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          google:
  #            client-id:
  #            client-secret:
  #            redirect-uri: http://localhost:8080/login/oauth2/code/google
  #            scope: openid,email,profile
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 2MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: alexeysitiy@gmail.com
#    password: arqkmemdnnyabqge
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
jwt:
  subject: "Username"
  issuer: "Ideas project"
  secret: "eyJhbGciOiJI"
  longevity: 180


aws:
  access:
    key:
      id: AKIATAVZMCPH4DPJRWQP
  secret:
    access:
      key: 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
  s3:
    region: eu-central-1
    bucket:
      name: springimagebucket
    projects-url: projects/
    users-url: users/

logging:
  level:
    root: info
    com.alexsitiy.ideas.project: debug


