app:
  user:
    default-avatars: defaultAvatar_1.png, defaultAvatar_2.png, defaultAvatar_3.png
  email:
    subject: "[IdeaProjects Team]"
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    open-in-view: false
  jackson:
    date-format: java.text.SimpleDateFormat
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 2MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  subject: "Username"
  issuer: "Ideas project"
  secret: ${JWT_SECRET}
  longevity: 180

aws:
  access:
    key:
      id: ${AWS_ID}
  secret:
    access:
      key: ${AWS_KEY}
  s3:
    region: eu-central-1
    bucket:
      name: ${AWS_BUCKET}
    projects-url: projects/
    users-url: users/


